import { v4 as uuid } from "uuid";

export const Habits = [
  {
    id: uuid(),
    habit: "Exercise",
    repeat: "Daily",
    goal: "1 time Daily",
    timeOfDay: "Any time",
    startDate: "Today",
  },
  {
    id: uuid(),
    habit: "Meditation",
    repeat: "Daily",
    goal: "2 times Daily",
    timeOfDay: "Morning",
    startDate: "Today",
  },
  {
    id: uuid(),
    habit: "Reading",
    repeat: "Daily",
    goal: "1 time Daily",
    timeOfDay: "Evening",
    startDate: "Today",
  },
  {
    id: uuid(),
    habit: "Water intake",
    repeat: "Daily",
    goal: "3 times Daily",
    timeOfDay: "Any time",
    startDate: "Tomorrow",
  },
  {
    id: uuid(),
    habit: "Yoga",
    repeat: "Daily",
    goal: "1 time Daily",
    timeOfDay: "Morning",
    startDate: "Tomorrow",
  },
  {
    id: uuid(),
    habit: "Writing",
    repeat: "Weekly",
    goal: "1 time Daily",
    timeOfDay: "Any time",
    startDate: "Tomorrow",
  },
  {
    id: uuid(),
    habit: "Language learning",
    repeat: "Weekly",
    goal: "2 times Daily",
    timeOfDay: "Evening",
    startDate: "After 2 days",
  },
  {
    id: uuid(),
    habit: "Healthy eating",
    repeat: "Monthly",
    goal: "1 time Daily",
    timeOfDay: "Any time",
    startDate: "After 2 days",
  },
  {
    id: uuid(),
    habit: "Cleaning",
    repeat: "Monthly",
    goal: "1 time Daily",
    timeOfDay: "Afternoon",
    startDate: "After 2 days",
  },
  {
    id: uuid(),
    habit: "Travel",
    repeat: "Yearly",
    goal: "1 time Daily",
    timeOfDay: "Any time",
    startDate: "After 3 days",
  },
];
